extra.set("kotlinVersion", "2.2.10")

extra.set("activityVersion", "1.10.1")
extra.set("appcompatVersion", "1.7.1")
extra.set("composeUiVersion", "1.8.1")
extra.set("constraintLayoutVersion", "2.2.1")
extra.set("coroutinesVersion", "1.10.2")
extra.set("fragmentVersion", "1.8.9")
extra.set("lifecycleVersion", "2.9.2")
extra.set("materialVersion", "1.12.0")
extra.set("recyclerviewVersion", "1.4.0")
extra.set("roomVersion", "2.7.2")

extra.set("gsonVersion", "2.11.0")
extra.set("readiumVersion", "3.1.1")
extra.set("retrofitVersion", "3.0.0")
